# Generated by Django 5.0 on 2024-01-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
